# Generated by Django 4.0 on 2021-12-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_menu_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isCanceled',
            field=models.BooleanField(default=False),
        ),
    ]
